config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "events#index"
  resources :users, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, :start_date, :end_date, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :events, dependent: :destroy

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new]
  before_action :no_edit_user, only: [:edit]
  before_action :show_login_check, only: [:show]
  before_action :limited_user, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    respond_to do |format|
      if @event.save
        UserMailer.send_mail(@event).deliver
        format.html { redirect_to @event, notice: '予約が登録されました。カレンダーに予約が反映されているか確認してください。' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: '予約内容が変更されました。カレンダーに変更が反映されているか確認してください。' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: '予約を取り消しました。カレンダーから消えているか確認してください。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date).merge(user_id: current_user.id)
    end

    def login_check
      unless user_signed_in?
        flash[:alert] = "予約するにはログインか新規登録をしてください"
        redirect_to new_user_session_path
      end
    end

    def no_edit_user
      if user_signed_in? && (!(current_user.id == @event.user_id)) && !current_user.admin
        redirect_to root_path
      end
    end

    def limited_user
      if user_signed_in? && (!(current_user.id == @event.user_id)) && !current_user.admin
        redirect_to root_path
      end
    end

    def show_login_check
      unless user_signed_in?
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
        
      if @user.save
        format.html { redirect_to @event, notice: '予約が登録されました。カレンダーに予約が反映されているか確認してください。' }
        format.json { render :show, status: :created, location: @event }
      else
        render 'new'
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @events = @user.events
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :encripted_password) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> 入力情報に誤り、もしくは未記入欄があります！</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="items-sell-main">
    <h2 class="items-sell-title">予約内容入力</h2>
    <div class="new-items">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span> ニックネームを記載してください。記載していただくと、急病などで営業出来ない場合は連絡先が分かれば店主から連絡が出来ます。
      </div>
      <%= form.text_area :title, class:"items-text", id:"item-name", placeholder:"名字(カタカナ)、またはニックネーム(１０文字まで)", maxlength:"10" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">空欄OK</span> 「髭剃りのみ希望(←この場合３０分)」、「白髪染めを希望(←この場合９０分)」、など通常のカットコース以外を希望する場合は記載してください。
        </div>
        <%= form.text_area :description, class:"items-text", id:"item-info", placeholder:"(30文字まで)" ,rows:"2" ,maxlength:"30" %>
      </div>
    </div>
   
    <div class="items-detail">
      <div class="weight-bold-text">予約日時</div>
      <div class="form">
        <div class="weight-bold-text">
          開始日時
          <span class="indispensable">必須</span> 開店時間ＡＭ９：００
        </div>
        <%= form.datetime_select :start_date, {datetime_separator: '<h4 class="fb-txt font-weight-bold my-2">時間</h4>', start_hour: 9, end_hour: 18, ampm: true, minute_step: 15}, class:"select-box" %>
        <div class="weight-bold-text">
          終了日時
          <span class="indispensable">必須</span> 閉店時間ＰＭ７：００
          <p>注：年月日を上と同じにしてください。<br>通常のカットコース予約なら開始時間から６０分後(１時間後)に設定してください)</p>
        </div>
        <%= form.datetime_select :end_date , {datetime_separator: '<h4 class="fb-txt font-weight-bold my-2">時間</h4>', start_hour: 9, end_hour: 19, ampm: true,minute_step: 15}, class:"select-box" %>
      </div>
    </div>
    
    <div class="sell-btn-contents">
      <%= form.submit "決定する" ,class:"sell-btn" %>
    </div>
 
<% end %>

app/views/events/edit.html.erb
<h1>予約内容変更</h1>

<%= render 'form', event: @event %>


<%= link_to '予約内容を表示', @event %> |
<%= link_to 'トップページに戻る', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="items-sell-title">本日から２週間先まで予約可能です</h1>
<h1 class="items-sell-title">予約するにはユーザー登録が必要です→<a href= /users >操作説明ページへ</a></h1>


<div id="calendar"></div>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= link_to 'トップページに戻る', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>説明:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>開始時間:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>終了時間:</strong>
  <%= @event.end_date %>
</p>

<% if user_signed_in? && current_user.id == @event.user_id %>
  <%= link_to '予約変更', edit_event_path(@event) %> |
  <%= link_to '予約取り消し', event_path(@event), method: :delete, data: { confirm: '予約を取り消すと元に戻せません。本当に取り消しますか？' } %> |
<% elsif  user_signed_in? && current_user.admin %>
  <%= link_to '予約変更', edit_event_path(@event) %> |
  <%= link_to '予約取り消し', event_path(@event), method: :delete, data: { confirm: '予約を取り消すと元に戻せません。本当に取り消しますか？' } %> |
<% end %>
<%= link_to 'トップページでカレンダーを確認する', events_path %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href= / >アート理容室予約カレンダー</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>さん
            <ul class="user__info">
              <li>
                <%= link_to "予約表示", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                <li><%= link_to '情報編集', edit_user_registration_path, method: :get %></li>
              </li>
            </ul>
          </span>
            <%= link_to '予約新規登録', new_event_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "ユーザー登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <font color="brack"><p>
        営業時間AM9時〜PM7時 毎週月曜、第二第三火曜定休日(その他年始年末休みなどカレンダーに表示されています)
      </p></font>
      <p>
        Copyright アート理容室 2020.
      </p>
    </footer>
  </body>
</html>

app/views/users/index.html.erb
<h1 class="description-title">ユーザー登録の手順</h1>
<p class='reason-list-description'>① 画面右上の「ユーザー登録」を押し、必要項目を入力して「登録する」を押してください。</p>
<p class='reason-list-description'>注）ニックネームは本名でも可能ですが本名が予約カレンダーに公開されてしまいます</p>
<p class='reason-list-description'>注）パスワードはご自身で覚えやすいものにしてください。パスワードを忘れるとログインが出来なくなり予約の変更が出来なくなります。</p>
<p class='reason-list-description'>注）メールアドレスが必要なのでアドレスが無い方はヤフーのフリーアドレスなどを開設してください。（詳しい方に頼んでください）</p>

<p class='reason-list-description'>② 登録するとメールが送信されます。登録した時と同じスマホ・パソコンでメール開き、リンクをクリックして認証を行ってください。</p>

<%= image_tag '2020-11-18 14.59.00', :size =>'400x400'%><br>
<p class='reason-list-description'>メールのリンクをクリックすると新しい画面が表示され、下記の表示が出ていれば登録成功です。</p>
<%= image_tag '2020-11-18 15.16.31', :size =>'400x400'%>
</p>

<h1 class="description-title">ログイン後、予約の登録手順</h1>
<p class='reason-list-description'>① まずカレンダーを見て、空いている時間を探します。</p>
<p class='reason-list-description'>画面右側の < > のボタンを押すと週が変わります。todayボタンを押すとカレンダーが本日に戻ります(本日は橙色で表示)</p>
<p class='reason-list-description'>空いている時間を確認したら画面の右上の「予約新規登録」をクリックしてください。</p>
<p class='reason-list-description'>(白髪染めや髭剃りのみ、パーマなど何時間かかるか分からない場合は電話にて問合せください)</p>
<%= image_tag '2020-11-18 14.57.37', :size =>'550x700'%>
<p class='reason-list-description'>② 予約が登録されると予約完了のメールが送られます。予約が登録されたらカレンダーを確認してください。</p>
<p class='reason-list-description'>下記画面のように登録した予約の枠が表示されます。この枠をクリックすると予約の詳細が見れます。</p>
<p class='reason-list-description'>この詳細は予約登録者と管理者(店主)のみが見ることができます。この詳細から予約の変更、取り消しも行えます。</p>
<%= image_tag '2020-11-18 15.51.41', :size =>'350x400'%>
<p class='reason-list-description'>注）カレンダーに下記の様な枠の表記がされている場合は間違った入力の可能性があります。修正してください。</p>
<p class='reason-list-description'>予約の変更はカレンダーの枠をクリックするか、マイページの予約表示から予約変更することができます。</p>
<%= image_tag '2020-11-18 16.03.05', :size =>'400x450'%>
<%= image_tag '2020-11-18 15.52.13', :size =>'400x450'%>
<p class='reason-list-description'>注）本当に稀ですが、予約のタイミングが重なってお客様の予約時間が重複してしまうことがあり得ます。</p>
<p class='reason-list-description'>注）下記画面の様に表記されている場合、nick様の予約完了時は重なっていなかったので、後から遅れて予約したのはニック様となります。</p>
<%= image_tag '2020-11-18 16.24.14', :size =>'400x450'%>
<p class='reason-list-description'>注）このケースの場合はニック様が３０分予約を遅くずらしていただく様お願い致します。</p>
<p class='reason-list-description'>注）どちらが遅れて予約したのか分からないケースは、両お客様が１５分早く変更、１５分遅く変更してもらい、重なった時間がないようにしていただけると幸いです。</p>
<%= link_to 'トップページに戻る', events_path ,class: "items-sell-title" %>
<p></p>

app/views/users/show.html.erb
<div class="contents row">
  <h1 class="notice-title"><%= @nickname %>さんの予約一覧</h1>
  
  <table>
  <thead>
    <tr>
      <th>名前</th>
      <th>説明</th>
      <th>開始時間</th>
      <th>終了時間</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% if @events.present? %>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.description %></td>
          <td><%= event.start_date %></td>
          <td><%= event.end_date %></td>
          <% if user_signed_in? && current_user.id == event.user_id %>
            <td><%= link_to '予約変更', edit_event_path(event) %></td>
            <td><%= link_to '予約取り消し', event_path(event), method: :delete, data: { confirm: '予約を取り消すと元に戻せません。本当に取り消しますか？' } %></td>
          <% end %>
        </tr>
      <% end %>
      <% else if %>
      <h1>登録している予約はありません</h1>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to 'トップページに戻る', events_path ,class:"notice-title"%>
</div>